version: '3.3'
services:
    frontend:
        image: $COMPOSE_PROJECT_NAME/frontend:$VERSION
        build:
            context: ../
            dockerfile: docker/frontend.Dockerfile
        ports:
           - $FRONTEND_PORT:3000
        restart: unless-stopped
    api:
        image: $COMPOSE_PROJECT_NAME/api:$VERSION
        build:
            context: ../
            dockerfile: docker/api.Dockerfile
        environment:
            CORS_ALLOWED_ORIGINS: $CORS_ALLOWED_ORIGINS
            API_ROOT_PATH: $API_ROOT_PATH
        restart: unless-stopped
        ports:
           - $API_PORT:8000
    streamlit:
        image: $COMPOSE_PROJECT_NAME/streamlit:$VERSION
        build:
            context: ../
            dockerfile: docker/streamlit.Dockerfile
        environment:
            CORS_ALLOWED_ORIGINS: $CORS_ALLOWED_ORIGINS
            STREAMLIT_SERVER_BASE_URL_PATH: $STREAMLIT_SERVER_BASE_URL_PATH
        ports:
           - $STREAMLIT_PORT:8501
